### ISSUE TITLE
Add some PRs from upstream

### ISSUE THREAD

**Issue by gizmo98** [RetroPie/EmulationStation#13]
Upstream was not updated for a while. There are some open PRs we could evaluate and use:
-Symlink support https://github.com/Aloshi/EmulationStation/pull/430
-Code fixes https://github.com/Aloshi/EmulationStation/pull/455
-Proper shutdown https://github.com/Aloshi/EmulationStation/pull/502
-Improve md hashing https://github.com/Aloshi/EmulationStation/pull/422

**Comment by joolswills** [comment]
https://github.com/Aloshi/EmulationStation/pull/430 looks good. I'll do a PR

https://github.com/Aloshi/EmulationStation/pull/455 has too many whitespace changes for my liking along with code changes and will mess up future merges no doubt.

The Shutdown is sorted, and the md hashing is for the gamesdb branch so we can leave those.

Any others of interest in other forks ? https://github.com/batkinson/EmulationStation has a few possible improvements

**Comment by joolswills** [comment]
(and recalbox - the favourites in recalbox is nice - I think it's a combination of some upstream PR, but they might have added their own changes too)

**Comment by joolswills** [comment]
Adding these for comment  - not checked the code etc, just ideas of things we could look into merging.

https://github.com/Aloshi/EmulationStation/pull/536 - Add a sort option for the scrapped name

https://github.com/Aloshi/EmulationStation/pull/517 - Hide mouse cursor early

Favourite changes (I guess we need one or the other)
https://github.com/Aloshi/EmulationStation/pull/344 - Add/remove a game from favorite feature
https://github.com/Aloshi/EmulationStation/pull/393 - Graphical Favorite list

**Comment by joolswills** [comment]
https://github.com/recalbox/recalbox-emulationstation/commit/61eafba14a145a89597207da64eac54f245a1f59 - recalbox favourites implementation based on above two patches. not compared it

**Comment by joolswills** [comment]
(recalbox made a bunch of changes to favourites after that patch too). We are probably best to just look at the upstream ones, as they will be less customised.

**Comment by zigurana** [comment]
(shameless plug)
My PR (https://github.com/RetroPie/EmulationStation/pull/32), is based on the Graphical Favorite list by Captainka (https://github.com/Aloshi/EmulationStation/pull/393).
(/shameless plug)

**Comment by JustinAiken** [comment]
:+1: for @zigurana's #32, would be amazing!

**Comment by Melkoroth** [comment]
Is the shutdown issue on Linux really sorted? I have to ctrl+alt+supr a couple of times for it to work, but maybe is just on my rpi3.

**Comment by MrTimscampi** [comment]
It should be noted that as of March 19th, the project is officially unmaintained: https://github.com/Aloshi/EmulationStation/issues/563#issuecomment-198787794

**Comment by sbowler** [comment]
How many years are you guys going to cling on that someone somewhere will pick this up upstream? It's now been over 2 years since anything was committed upstream. Are you planning to drop emulation station or something? I believe Recalbox is starting to leave you in the dust in large part because you refuse to pull in any upstream pull requests. Due to current MIT licensing you could even shamelessly steal half of Recalbox's code probably with minimal effort. I like the way you guys do your build and some things better, but until you add favorites at least I will probably have to stick with Recalbox.

**Comment by joolswills** [comment]
Trolling ? Feel free to continue using recalbox.

**Comment by sbowler** [comment]
Seriously? That's your response? This is a legitimate concern that you apparently felt the need to leave this issue open for over a year with little traction. Is there an official stance or policy on emulation station in regards to Retropie since emulation station is dead?

**Comment by joolswills** [comment]
Yes - based on your post.

What are you talking about ? Just because we haven't implemented favourites you feel the need to have a moan. Have you even checked the commit log ? Our fork is in active development. We have different goals from Recalbox. If you don't like our aims - fine - but moaning on this thread isn't going to help.

**Comment by hex007** [comment]
Are any updates expected from this or can this be closed?

**Comment by joolswills** [comment]
Yeah. Can be. Thanks
