### ISSUE TITLE
Improve settings in GUI

### ISSUE THREAD

**Issue by dantheman213** [RetroPie/EmulationStation#21]
Settings shouldn't be located as ab "emulator" option in the software. It doesn't make sense to mix apples and oranges in the same UI paradigm.

I think we should split out the settings as a button at the header or footer on the screen.

On that screen the settings should be more streamlined. All options should keep you within the GUI and execute any scripts/programs in the background and return the output nicely within the GUI.

In addition, all reasonable settings should be able to be modified using a controller gamepad.

No keyboard should be necessary while working within the settings area.

**Comment by joolswills** [comment]
not sure what you mean exactly, but if you mean the retropie-setup configuration, this will always be separate from ES.

**Comment by smartroad** [comment]
Is there anyway to hide the retropie-setup from the main menu? Just thinking I have some friends and their boy loves playing the old games, I just worry that he could accidentally mess with settings. Not that it is a big issue, just a waste of time setting everything back! lol

**Comment by joolswills** [comment]
Did you google it ?

https://www.reddit.com/r/RetroPie/comments/33gz62/retropie_30_hide_retropie_option_menu/

Please use the RetroPie forum for support etc. Cheers.

**Comment by dantheman213** [comment]
I'm just saying that it's very peculiar that a) the settings are located in the same exact location as your video game consoles and b) some of the settings execute outside of EmulationStation GUI and even require separate input devices like a keyboard.... none of that is really in the spirit of a classic gaming console. It should all be integrated smoothly into EmulationStation and all controlled from a controller with optional default keyboard support.

**Comment by joolswills** [comment]
because it is completely separate from emulationstation - it's not feasible to integrate all our options into ES. If you want a more integrated system, try recalbox.

**Comment by joolswills** [comment]
Sorry, but this just isn't something we have planned, nor is it really doable currently. I think having the settings at least accessible within ES does work for most. You can remove them from there as needed, if you think it makes it seems more integrated.

**Comment by dantheman213** [comment]
@joolswills Why is this not feasible? I'm a senior engineer and I've spent a lot of time writing embedded C++ applications... surely you can execute scripts or commands in the background and provide a clean GUI? You've already done 90% of the work... why not take it the last step to give it that "polished Apple feel"?

**Comment by joolswills** [comment]
It's not the direction we want to take. ES development has also stopped upstream so we may include other frontends in the future. it really makes no difference imho to functionality accessing the menu options from the retropie system - and allows users to easily add their own scripts.

**Comment by dantheman213** [comment]
@joolswills thanks for letting me know that you're not interested in building quality software; saved me from spending any time on this.

**Comment by joolswills** [comment]
how rude.

**Comment by gizmo98** [comment]
I like the idea moving retropie "system" into emulationstation menu. I already played around with this thought for a while. It makes sense because the current retropie menu looks mixed up. There is no explanation for every item. Audio output settings should be under AUDIO. ASplashscreen should be under VIDEO or SYSTEM. RetroPie-Setup and retropie/retroarch config should be under a RETROPIE item. IP address and WLAN setup should be under NETWORK and so on.

On the other hand i don't want to invest much time in this for now. It's sad Aloshi is not working on this any longer. As jools said upstream development stopped. So if we use another frontend in the future any work here would be a waste of time. 

If you need a 100% controller configurable system use recalbox or lakka tv.

**Comment by dantheman213** [comment]
@gizmo98 no murmurs on forking the project with a new team or creating a new frontend project entirely?

**Comment by joolswills** [comment]
@gizmo98 it still wouldn't be integrated since we manage everything externally, unless you mean we rework like recalbox the functionality into ES completely - things like bluetooth though etc would then require a significant amount of custom code. I was thinking though regarding having more frontends or if we offered another like attractmode, that the way we do it currently is at least flexible and easy to expand upon. Also the options are usually set up once only. 

I'm happy with our current compromise, until we are clearer where we are going. I was thinking we might need to resurrect InputStation again too, if we will offer an alternative frontend.

**Comment by joolswills** [comment]
@gizmo98 another compromise would be to ditch the retropiemenu system and have a single retropie-setup launcher in the settings, which wouldn't require much work - but it would still exit ES to launch our shell code though, so it's not a fix for anything beauty wise.

**Comment by joolswills** [comment]
(although some users do use that I think for their own scripts)

**Comment by gizmo98** [comment]
@Jools 
Do you think it is a problem launching some things (configedit, raspi-config, retropie-setup) from menu instead of retropie system view? We can still put some macros around this code so someone can build es without retropie stuff.

**Comment by gizmo98** [comment]
@Jools
I just meant to launch our scripts there or start exposed functions of our scripts. I don't have any interest rewriting everything in C++.

**Comment by joolswills** [comment]
I don't have a problem with that if you have the time to implement it, but we should possibly keep the retropie system functionality in place but perhaps disabled by default, for those that want to launch custom scripts from it.
