### ISSUE TITLE
Video Scrensaver is BLACK if an ES Menu is Open

### ISSUE THREAD

**Issue by chewvodka** [RetroPie/EmulationStation#245]
Just making an official BUG post here for this.  It was reported in the forums but never fixed.  Essentially, if you have the Video Screensaver enabled, and are in the ES menus (from pressing START or SELECT to change various options), the screensaver just loads up a black screen.  It's probably a rare case, since most people would do whatever they need to do in those menus then have them closed out.  I've had the issue come up more frequently since I'm typically doing something, then swapping video inputs on my TV to update a forum post or something and the screensaver timeout triggers.  Still, it is a BUG, and is easily duplicatable.

**Comment by pjft** [comment]
Thanks.

True. I've experienced this quite a few times, but didn't necessarily consider it "high impact" enough. Sorry about that.

It certainly is something I should look into. I know exactly why that happens, I'm not quite sure how to fix it without breaking other things though. I'll have to dig into the code, and tread carefully.

Thanks.

**Comment by chewvodka** [comment]
No worries.  :)  I was just making it official.  It's probably not high impact at all.

**Comment by hex007** [comment]
Is this still reproducible on RPi ? On Linux screensaver is launched works as expected.

**Comment by pjft** [comment]
Hm.

It should certainly be reproducible. 

It is related to the following code, in VideoComponent.cpp.

In the constructor:
```
if (mWindow->getGuiStackSize() > 1) {
		topWindow(false);
	}
```

and then

```
void VideoComponent::topWindow(bool isTop)
{
	mDisable = !isTop;
	manageState();
}
```

Effectively, when we have an open menu, the GuiStackSize will be greater than one, so we won't consider the Video window to be on top, and will be disabled alas. I'm also aware that this was mostly put in place to prevent the video to keep playing in the background when the menu was open, so that's an unintended byproduct of that.

Maybe that constructor guard should check for whether the video is a screensaver video or not.

I can try to look into this in the coming days, as writing about it seems to suggest a potential fix, so it shouldn't be too much of a pain to code it in my current Pi-based, nano-based development environment.

Thanks for bumping this issue!

**Comment by hex007** [comment]
So this only affects video screensaver. 

@pjft What is the harm of letting video play in background when menu is open?

**Comment by pjft** [comment]
Nothing extremely significant other than background noise, but problematic with OMX Player as it renders on top of the ES window. Also, if you edit the metadata and change the video metadata or remove the game while the video is playing, I'm not really sure what's going to happen.

**Comment by chewvodka** [comment]
Cool, so just to clarify.. update ES from source and the fix will go? :)

**Comment by pjft** [comment]
Right now I actually think you can just install from binary and you should be good to go.

**Comment by 2play** [comment]
ES 2.9.6rp 
Black screen seems to be back if in menu, fo Random Video Screensaver the OMX is set ON to be used
Another weird is that game stopped to start by pressing a key

- with omx on video scv i get black screen only
- an external subs error with the omx on show when you exit to cli
- a,b,x,y key just exit scv, and SELECT goes to next random video

Tested also ES 2.9.3rp with same. Has something changed or this after DEC OS upgrade?

**Comment by pjft** [comment]
There's an option in the menu that needs to be enabled to start the game from the screensaver, and START is the key that starts the game, no other.

OMX doesn't work properly on the Pi4 for subtitles. If it doesn't work on the Pi3 as well now, then it's probably because of an upgrade. Use VLC on the Pi4.

Please resort to the forums for this kind of questions rather than posting on a closed issue from over 3 years ago. Thanks.

**Comment by 2play** [comment]
Thank you. I already did on forums and saw this too as it was weird that it came back.
Thank you  for your reply!
