### ISSUE TITLE
The DELETE button on the EDIT METADATA screen should only delete the metadata, not the game itself

### ISSUE THREAD

**Issue by c0d3h4x0r** [RetroPie/EmulationStation#505]
It is unexpected that the DELETE button on the EDIT METADATA dialog deletes more than just the metadata.  Either add a separate CLEAR button for clearing just the metadata, or change the behavior of the DELETE button to only delete the metadata.

**Comment by cmitu** [comment]
I guess you're just requesting a 'Clear metadata' option. The **delete** button does what it says - deletes the ROM.

**Comment by c0d3h4x0r** [comment]
No, that's not all I'm looking for.  I'm on the "EDIT METADATA" dialog, so I would expect a DELETE button in that context to delete the metadata only, since the dialog is purely about the metadata.

**Comment by c0d3h4x0r** [comment]
And to clarify -- the **DELETE** button currently does **more** than it says.  From all appearances, it says it will delete the metadata.  I experienced unexpected userdata loss when I clicked it and discovered it had actually deleted the underlying game ROM.

**Comment by pjft** [comment]
Thanks for the report. We understand the frustration and the potential inconsistency in semantics, but there’s no need to add the bold format to the words. Truth be told, it’s been like that for the past handful of years, even from when Aloshi started the project. In all these years maybe a handful in total have experienced this issue.

To be fair, the delete button pops up a message saying “THIS WILL DELETE A FILE! ARE YOU SURE?”. If users don’t read the message, then that’s that, but it doens’t qualify as “from all appearances it says it will delete the metadata”. If you want a button to delete the metadata, that’s a separate use case.

As far as I’m concerned, changing the button’s behavior is a non-issue, though if someone does want to submit a PR to change the behavior (meaning, keeping the file deletion option but adding the option to just clear metadata) I imagine it’d be more than welcome, but other than that please understand that this is the way it is intended to work.

Thanks.

**Comment by c0d3h4x0r** [comment]
At the very least, the message should be changed to clarify which file(s) will be deleted... even saying "THIS WILL DELETE THE ACTUAL GAME FILE(S)" would be much clearer.

**Comment by c0d3h4x0r** [comment]
"This is the way it is intended to work" is never a good justification for poor UX design.

**Comment by HerbFargus** [comment]
>This is the way it is intended to work" is never a good justification for poor UX design.

Just because you deem a feature a bug and call it bad UX design isn't going to fix it. Source code is open, nobody here is paid so feel free to submit a well written pull request with a solution

**Comment by c0d3h4x0r** [comment]
Alright, I will.  Which branch should I prepare a pull request against -- master?  stable?  unstable?

**Comment by c0d3h4x0r** [comment]
But I should also point out that expecting all users to also be developers is not a reasonable expectation.  In this case, I just happen to also be a developer... but if I weren't, it wouldn't mean my feedback about the UX would be invalid.

**Comment by pjft** [comment]
To be clear, nobody is saying that “this is the way it is intended to work” is a justification for poor UX design by itself. As I stated in my first post, data does back this up - the project has been live since 2015 at least, and out of thousands (tens of thousands? Hundreds of thousands?) of users, this specific issue/report isn’t frequent enough to warrant changing the behavior for everyone else who uses it this way.

There is a valid use case for deleting a game from within ES. The game may not work, it may be a duplicate, etc. 

There might certainly be a valid use case for clearing the metadata, sure - nothing prevents it from being done from with ES manually right now, but sure. 

There is no other area within ES where the “delete a file” use case would be appropriate, so this is where it is. Is it ideal? Maybe not. Is it a bug? No. Is it an issue worth spending this much time battling to convince that, compared to all the other things that can be fixed (or further developed), this is the a really pressing one since people might delete their game files by mistake? It’s not that the feedback isn’t valid, as much as it is so that most people have so far understood what it was meant to do.

As Herb said, it’s open source, and if someone wants to take a stab at it, it’ll be very much appreciated. Making the message clearer might be the best approach, as removing the use case isn’t ideal. Adding a button to clear metadata may also be appropriate if you’d like it to be, but UI-wise it might not be ideal. 

Your call, really.

Submit changes to master, that’s where usually the latest version of the code is.

Thanks!

**Comment by c0d3h4x0r** [comment]
Thanks!  I'll prep a pull request to master.  Changing the message is an acceptable enough UX correction.

**Comment by pjft** [comment]
Perfect - thank you! GuiMetaDataEd.cpp is where you’ll want to change things, I believe.

**Comment by c0d3h4x0r** [comment]
Looks like I don't have permission to create my own branch of RetroPie/EmulationStation.  Do I really have to make a fork in order to create a pull request?  If so, I'm going to need to figure out how to create a secondary fork within my GitHub account, because I already have an existing fork of Aloshi/EmulationStation, and hitting the "Fork" button on RetroPie/EmulationStation just takes me to that one.

**Comment by c0d3h4x0r** [comment]
Looks like GitHub doesn't sensibly support multiple forks under a single user account, so I just deleted my fork of Aloshi/EmulationStation.  (I guess I'll have to recreate a relevant pull request I had already created off of it.)

**Comment by c0d3h4x0r** [comment]
See pull request [https://github.com/RetroPie/EmulationStation/pull/507](https://github.com/RetroPie/EmulationStation/pull/507).
