### ISSUE TITLE
[Feature Request] Ability to suppress platform suffix in game names inside custom collections

### ISSUE THREAD

**Issue by jueank** [RetroPie/EmulationStation#544]
Currently, all game titles in detail list of ES show brackets with the platform name as a suffix when they are part of custom collections. E.g. Centipede [arcade] This is irritating, because game titles are less readable. Especially if this is shown in every line. Also for longer game titles, this takes lot of screen space horizontally in the list.
I have custom collections which are only subsets of one platform. Therefore, there's not benefit in having the platform appended anyhow.
I would like to have a config option (does not have to be in the UI, config file is perfectly fine) to define if this suffix is shown or not.

**Comment by pjft** [comment]
If you want to take a stab at it, I'll gladly point you in the right direction.

You're looking to change this function here:

https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/FileData.cpp#L343

And add an option for it.

Otherwise, in general it's usually best to post and discuss feature requests in the forums.

**Comment by jrassa** [comment]
option added in #571
