### ISSUE TITLE
Kid mode does not have "shut down" option

### ISSUE THREAD

**Issue by apassiou** [RetroPie/EmulationStation#556]
When in Kid mode, Start button does not bring up the menu with option to shut down.

**Comment by pjft** [comment]
Correct, that is by design. It's meant to be a mode where you can leave the kids to play without risking them being able to exit or break things.

If you're looking for a more locked down mode, Kiosk mode would be what you're looking for.

Still, for such feedback we recommend going to the forums at https://retropie.org.uk/forum/

Thanks.

**Comment by apassiou** [comment]
But by this design it is precisely the problem that I cant leave the kids with the retropie to play their games. I have to ssh into it and shut it down via a command in order for them to move to a different TV or turn it off for any other reason. Alternative is to leave it on 24/7 and never move it. Which is just unrealistic. 

I view kid mode allowing the kid to do no more and no less what a standalone console from our childhood would allowed us to do. And that is precisely to have a Power button, reset button (to restart the game), and select a game. 100% of use time for my retropie is my kids, but without power off functionality it seems like a very impractical mode that I cannot use. Worse off, in order for me to shut it down I have to exit kid mode and select to shut down, but then I cant leave turned off retropie with the kids, because next time they will power it on it wont be in kid mode.

Can you explain how powering down from the menu can be harmful in any way? Seems like it would only be a positive thing.

**Comment by pjft** [comment]
> But by this design it is precisely the problem that I cant leave the kids with the retropie to play their games. I have to ssh into it and shut it down via a command in order for them to move to a different TV or turn it off for any other reason. Alternative is to leave it on 24/7 and never move it. Which is just unrealistic.

I'll say it again. Kiosk mode does what you're describing - it locks things similarly to what you want, and keeps the shutdown options and audio. That is an alternative which I'm not sure why you are not even considering or exploring it.

https://github.com/RetroPie/RetroPie-Setup/wiki/Child-friendly-EmulationStation

> Can you explain how powering down from the menu can be harmful in any way? Seems like it would only be a positive thing.

Because some "kids" will power it down by mistake and then won't know how to power it on. "Kids" are a very loosely defined term - maybe yours are autonomous enough to know how to turn it on by themselves, whereas younger ones might not be (or powering it on isn't just accessible). That was the intended design, and it's a use case that has been around since 2016 with hundreds of users relying on it and without complaints.  It's not intended to force people to yank the cord.

Unless you can share the very specific reason why you can't use Kiosk mode for what you're trying to accomplish, it's hard to try to help you accomplish what you're going for. You can use Kiosk mode, or if you _really_ insist in only using Kids mode, you could add a custom script to the RetroPie menu that invokes 'sudo shutdown now' or some other solution - as I stated, the forums are the best place to discuss alternatives and approaches as I'm sure that others may have gone through similar challenges as well (myself included).

Hope this helps.

**Comment by apassiou** [comment]
I did attempt using Kiosk mode, but it does not obey "kid game" flag. So instead of labeling a dozen or so games from thousands and taking a minute, I would have to set (thousands-dozen == still thousands) games to hidden, which would take many hours, if not days. So unless I missed something kiosk mode is not usable for only whitelisting a few games (and then whitelisting more and more as the kids get older).

Also, from what I saw in Kiosk mode RetroPie Setup is still surfaced and navigable.

Ill admit I did not explore Kiosk mode much since Kid mode seemed perfect and I assumed power option not showing up was a bug (or there was some key combo to do it).

I guess my options are to either add a physical button or to just fork the repo and add it myself. I think a kid that can navigate to shut down is cognizant enough to know that unplug/reply will power it back up. 

At the very least the option to add shutdown to kid mode should be configurable as there is practical use to it. But this is your repo, so if you disagree I cant do anything about that. Thank you for at least answering this I guess. 

This was posted on the forum to no replies https://retropie.org.uk/forum/topic/21836/how-to-shut-down-retropie-while-in-kid-mode

And if your users have to come up with creative solutions to "work around" your design. Then something is wrong with your design. Just my opinion.

Thank you for your time.

**Comment by pjft** [comment]
Ah, got it, you're right. The use case is the opposite in that you specifically the files to choose vs to hide. 

I mean, if you want to develop that button as an option do submit the PR, I don't think anyone will fundamentally object to it. And it's probably better to keeping multiple outdated forks. 

Alternatively you could just create a shell script that calls 'sudo shutdown now' and invoke it from the RetroPie menu. This item would need to be visible in Kid mode, so added to the gamelist and set to kid=true. 

Certainly would fall more under the workaround scope but, as stated, that is not what the mode was designed for. And, just to build on top of your last remark, I'd agree if that'd be a more prevalent need, but if not the remark can also go the other way - that you're trying to use the current design for something it was not intended to.  As I said, this mode had existed in the wild side 2016 and this is not a common use case even though there are users of the mode. 

Still, that's not the point. 

Hope these help and indeed if you go down the route of implementing it in ES, do send it over as an option if possible. But the command line script will also probably work just fine if it suits your needs.

Best, and let us know what you end up deciding.

**Comment by apassiou** [comment]
Sounds good. I ordered the hardware for the button, but at some point down the road I think I will still add the code and submit as well. Thanks.

**Comment by pjft** [comment]
Sounds good. The button will only call "sudo shutdown now" as well so if it's for shutting down it's equivalent to the script I suggested. 

Thank you and all the best with your setup!
