### ISSUE TITLE
"edit metadata" option doesn't work when "save metadata on exit" is on

### ISSUE THREAD

**Issue by meleu** [RetroPie/EmulationStation#66]
Two users recently reported different issues when  editing metadata. The problem was "solved" after disabling "save metadata on exit".
IMHO the "edit metadata" option should not be available when "save metadata on exit" is on.

Forum topics:
https://retropie.org.uk/forum/topic/4041/freezing-when-editing-metadata

https://retropie.org.uk/forum/topic/3979/edited-game-rom-metadata-not-being-saved

**Comment by pjft** [comment]
Hi, and thanks for raising it. Is this still an issue? I can't say I've experienced this, and I have the option on and have edited metadata recently, I believe.

Maybe it was fixed with the changes to improve the speed of saving metadata?

I asked Dominus, who reported it, so we can hopefully close it if it's solved.

**Comment by meleu** [comment]
Will check it soon. Thanks bro!

**Comment by meleu** [comment]
Not an issue anymore.
