### ISSUE TITLE
Font.cpp:410: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by Ripaw** [RetroPie/EmulationStation#718]
I installed RetroPie following the instructions on https://retropie.org.uk/docs/Debian/ in Ubuntu 20.04.1 LTS.
PC Specs: Pentium 4 3.2 GHz, 2 GB RAM, nVidia Geforce 210 1 GB (OpenGL 3.0).

When RetroPie launches, the screen go black and closes. After looking in forums I tried running in the terminal /opt/retropie/supplementary/emulationstation/emulationstation.sh --debug. This is the error:

```
emulationstation: /home/arcade/RetroPie-Setup/tmp/build/emulationstation/es-core/src/resources/Font.cpp:410: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.
Aborted (core `dumped)`
```

The log file $HOME/.emulationstation/es_log.txt it's empty.
I removed and then reinstalled the core package emulationstation and it's not solving the issue.

Please help :(

**Comment by cmitu** [comment]
Please use the forum, as directed in in the issue template.

**Comment by rafa-lee** [comment]
Having the same issue and it behaves just like @Ripaw described. It seems this is rather rare and somewhat recent, because I only found it here and in a german forum [https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiw08iM3rDtAhUeH7kGHX8OBQoQFjADegQIBBAC&url=https%3A%2F%2Fdosreloaded.de%2Fforum%2Findex.php%3Fthread%2F3783-der-retropi-emulationstation-thread-nicht-nur-f%25C3%25BCr-den-pi%2F&usg=AOvVaw0IHATg1lBzQiPRKcqQMEzS](url)

I'm running Kubuntu 20.04, Plasma Version 5.18.5, 48GB RAM, RX580, OpenGL 4.6
