### ISSUE TITLE
When I sort the game list, the highlighted game doesn't appear between the new relocated games I got after the sorting action. 

### ISSUE THREAD

**Issue by JoseFC3000** [RetroPie/EmulationStation#798]
Hello.
When I sort the game list (by name, publisher, system, etc...) I got (sometimes) a result where I can't see the highlighted game I had selected prior to the sort action. Looks like the list position go to a random position and the highlighted game is lost.
This happens depending on the game I select... I don't know why.
Of course, this issue happens when I have more titles than the maximun number of titles can be shown on screen.
This didn't happen in version 2.10.2.

**Comment by pjft** [comment]
We'd encourage reporting these in the forums, but since you're here, please provide more details:
- What theme are you using / does it matter?
- If you can replicate consistently, please provide those. If not, a video or something might help.
- What times can you consistently _not_ reproduce the issue?

Thanks.
