### ISSUE TITLE
Feature Request: Superior alternative to video snaps.

### ISSUE THREAD

**Issue by TomTurbine** [RetroPie/EmulationStation#799]
https://github.com/libretro/RetroArch/issues/14199

Requested this with Retroarch for them to tell it might already be possible.

Instead of loading up a video snap, load up the emulator + core and play a movie of it. At least for the smaller games.

The games are typically smaller than the video snap to begin with or close to it, loads up just as quickly and takes up about as much resources to run the snap as it does the game or more. And while the snap can by anywhere from 3-15MB each, the emulator movie is only about 30kb or so from what I can tell and would look far superior to the snap as it would be the actual game running with the settings you have configured.

Could replace 1GB of video snaps with 1MB of movie files and get better looking results for about the same resources or less.

**Comment by cmitu** [comment]
I'm not sure I understand what 

> _load up the emulator + core and play a movie of it

means ?. What is an 'emulator movie'  - can you be more specific and give some examples ?


I don't see this could replace the video snapshots in EmulationStation. 
Video support in the gamelist means a preview of the game can be seen directly from the front-end/gamelist, without forcing the user to start the game.

**Comment by TomTurbine** [comment]
Many emulators will actually allow you to record a movie file of the game. It's the emulator running the actual rom from a save state and doing the actions you put in doing it. Made one using Mesen before and a 30 second movie in it was about 6kb. Never tried it under RetroArch by I believe they have that functionality as well.

What I am describing it that instead of loading up a video file, it just loads up the rom itself and plays one of those movie files, at least for the older systems.

When it comes to the older systems, the games don't really load any slower than the videos or use much more in resources to run them. So when it came to stuff like the Atari2600, NES, or even N64, loading one of them up would be better than the movies as they would look better, load about as fast and take up less resources to do it.

**Comment by pjft** [comment]
I think I understand what you're going for, but if I'm getting it right, there are several reasons why this isn't something that is going to be pursued, at least at this stage. Let me share a few of the constraints:
- For one, theming implies that the video previews are rendered in specific screen positions and layers (meaning, we might have transparent overlays on top of the video that's playing, for specific effects. Invoking a separate process to render gameplay straight from the emulator would make that hard, if not impossible.
- Second, precisely because of theming, we would have to invoke the emulator to run in a fake window, of the right size and screen location as in the theme. Given that - at least on the Pi - we are not running in an environment with a window manager (and even if we were?), making that work would probably be too much of a hassle.
- Third, not all emulators would support that. Maybe RetroArch could - I don't know - but there are lots of emulators thar aren't RetroArch based. We would still need to keep the current video mechanisms for those.
- Also, input captures: I don't know what to expect when the emulator is running something on screen, even if playing back a recording. When I want to navigate the EmulationStation menu, what capture the inputs? EmulationStation? The emulator?

To be clear, if someone would want to take this on - and make it work across the multiple OS's we support, sure we'd consider it. But given the complexity, and marginal improvement for users from this implementation, we appreciate the suggestion - and informing us of this option - but we are not going to explore this at this stage.

Hope it helps.

Regards.
