### ISSUE TITLE
Game no working

### ISSUE THREAD

**Issue by AislanPenha** [RetroPie/EmulationStation#870]
When play Winning Elevel 3, doesn't go beyond the screen press star.

**Comment by cmitu** [comment]
That's not an issue for EmulationStation, which is just a game browser/launcher front-end. Once a game is started, everything happens in the emulator/program/port and it's not under EmulationStation's control.
If you're using RetroPie, you can ask in the [support forums](https://retropie.org.uk/forum/category/8/help-and-support), otherwise try to find a gaming community closer to your game that may offer assistance.
